# permissions for end users to edit cronhpas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cronhpa-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-cronhpa-controller
    app.kubernetes.io/part-of: kube-cronhpa-controller
    app.kubernetes.io/managed-by: kustomize
  name: cronhpa-editor-role
rules:
- apiGroups:
  - autoscaling.zhengyansheng.com
  resources:
  - cronhpas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.zhengyansheng.com
  resources:
  - cronhpas/status
  verbs:
  - get
